/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cgo_TYPES_H
#define cgo_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>




class Game;

class InvalidOperation;

typedef struct _Game__isset {
  _Game__isset() : name(false), host(false), port(false) {}
  bool name :1;
  bool host :1;
  bool port :1;
} _Game__isset;

class Game {
 public:

  Game(const Game&);
  Game& operator=(const Game&);
  Game() : name(), host(), port(0) {
  }

  virtual ~Game() throw();
  std::string name;
  std::string host;
  int32_t port;

  _Game__isset __isset;

  void __set_name(const std::string& val);

  void __set_host(const std::string& val);

  void __set_port(const int32_t val);

  bool operator == (const Game & rhs) const
  {
    if (!(name == rhs.name))
      return false;
    if (!(host == rhs.host))
      return false;
    if (!(port == rhs.port))
      return false;
    return true;
  }
  bool operator != (const Game &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Game & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(Game &a, Game &b);

inline std::ostream& operator<<(std::ostream& out, const Game& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _InvalidOperation__isset {
  _InvalidOperation__isset() : err_code(false), why(false) {}
  bool err_code :1;
  bool why :1;
} _InvalidOperation__isset;

class InvalidOperation : public ::apache::thrift::TException {
 public:

  InvalidOperation(const InvalidOperation&);
  InvalidOperation& operator=(const InvalidOperation&);
  InvalidOperation() : err_code(0), why() {
  }

  virtual ~InvalidOperation() throw();
  int32_t err_code;
  std::string why;

  _InvalidOperation__isset __isset;

  void __set_err_code(const int32_t val);

  void __set_why(const std::string& val);

  bool operator == (const InvalidOperation & rhs) const
  {
    if (!(err_code == rhs.err_code))
      return false;
    if (!(why == rhs.why))
      return false;
    return true;
  }
  bool operator != (const InvalidOperation &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InvalidOperation & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
  mutable std::string thriftTExceptionMessageHolder_;
  const char* what() const throw();
};

void swap(InvalidOperation &a, InvalidOperation &b);

inline std::ostream& operator<<(std::ostream& out, const InvalidOperation& obj)
{
  obj.printTo(out);
  return out;
}



#endif
