/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cgo_CONSTANTS_H
#define cgo_CONSTANTS_H

#include "cgo_types.h"



class cgoConstants {
 public:
  cgoConstants();

};

extern const cgoConstants g_cgo_constants;



#endif
