/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cg_CONSTANTS_H
#define cg_CONSTANTS_H

#include "cg_types.h"



class cgConstants {
 public:
  cgConstants();

};

extern const cgConstants g_cg_constants;



#endif
