/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "cgo_constants.h"

namespace cgo {

const cgoConstants g_cgo_constants;

cgoConstants::cgoConstants() {
}

} // namespace

