/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef GameLobby_H
#define GameLobby_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "cgo_types.h"

namespace cgo {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class GameLobbyIf {
 public:
  virtual ~GameLobbyIf() {}
  virtual bool signup(const std::string& username, const std::string& password) = 0;
  virtual bool signin(const std::string& username, const std::string& password) = 0;
  virtual bool fetch_game(const Game::type g) = 0;
};

class GameLobbyIfFactory {
 public:
  typedef GameLobbyIf Handler;

  virtual ~GameLobbyIfFactory() {}

  virtual GameLobbyIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(GameLobbyIf* /* handler */) = 0;
};

class GameLobbyIfSingletonFactory : virtual public GameLobbyIfFactory {
 public:
  GameLobbyIfSingletonFactory(const boost::shared_ptr<GameLobbyIf>& iface) : iface_(iface) {}
  virtual ~GameLobbyIfSingletonFactory() {}

  virtual GameLobbyIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(GameLobbyIf* /* handler */) {}

 protected:
  boost::shared_ptr<GameLobbyIf> iface_;
};

class GameLobbyNull : virtual public GameLobbyIf {
 public:
  virtual ~GameLobbyNull() {}
  bool signup(const std::string& /* username */, const std::string& /* password */) {
    bool _return = false;
    return _return;
  }
  bool signin(const std::string& /* username */, const std::string& /* password */) {
    bool _return = false;
    return _return;
  }
  bool fetch_game(const Game::type /* g */) {
    bool _return = false;
    return _return;
  }
};

typedef struct _GameLobby_signup_args__isset {
  _GameLobby_signup_args__isset() : username(false), password(false) {}
  bool username :1;
  bool password :1;
} _GameLobby_signup_args__isset;

class GameLobby_signup_args {
 public:

  GameLobby_signup_args(const GameLobby_signup_args&);
  GameLobby_signup_args& operator=(const GameLobby_signup_args&);
  GameLobby_signup_args() : username(), password() {
  }

  virtual ~GameLobby_signup_args() throw();
  std::string username;
  std::string password;

  _GameLobby_signup_args__isset __isset;

  void __set_username(const std::string& val);

  void __set_password(const std::string& val);

  bool operator == (const GameLobby_signup_args & rhs) const
  {
    if (!(username == rhs.username))
      return false;
    if (!(password == rhs.password))
      return false;
    return true;
  }
  bool operator != (const GameLobby_signup_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const GameLobby_signup_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class GameLobby_signup_pargs {
 public:


  virtual ~GameLobby_signup_pargs() throw();
  const std::string* username;
  const std::string* password;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _GameLobby_signup_result__isset {
  _GameLobby_signup_result__isset() : success(false), e(false) {}
  bool success :1;
  bool e :1;
} _GameLobby_signup_result__isset;

class GameLobby_signup_result {
 public:

  GameLobby_signup_result(const GameLobby_signup_result&);
  GameLobby_signup_result& operator=(const GameLobby_signup_result&);
  GameLobby_signup_result() : success(0) {
  }

  virtual ~GameLobby_signup_result() throw();
  bool success;
  InvalidOperation e;

  _GameLobby_signup_result__isset __isset;

  void __set_success(const bool val);

  void __set_e(const InvalidOperation& val);

  bool operator == (const GameLobby_signup_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(e == rhs.e))
      return false;
    return true;
  }
  bool operator != (const GameLobby_signup_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const GameLobby_signup_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _GameLobby_signup_presult__isset {
  _GameLobby_signup_presult__isset() : success(false), e(false) {}
  bool success :1;
  bool e :1;
} _GameLobby_signup_presult__isset;

class GameLobby_signup_presult {
 public:


  virtual ~GameLobby_signup_presult() throw();
  bool* success;
  InvalidOperation e;

  _GameLobby_signup_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _GameLobby_signin_args__isset {
  _GameLobby_signin_args__isset() : username(false), password(false) {}
  bool username :1;
  bool password :1;
} _GameLobby_signin_args__isset;

class GameLobby_signin_args {
 public:

  GameLobby_signin_args(const GameLobby_signin_args&);
  GameLobby_signin_args& operator=(const GameLobby_signin_args&);
  GameLobby_signin_args() : username(), password() {
  }

  virtual ~GameLobby_signin_args() throw();
  std::string username;
  std::string password;

  _GameLobby_signin_args__isset __isset;

  void __set_username(const std::string& val);

  void __set_password(const std::string& val);

  bool operator == (const GameLobby_signin_args & rhs) const
  {
    if (!(username == rhs.username))
      return false;
    if (!(password == rhs.password))
      return false;
    return true;
  }
  bool operator != (const GameLobby_signin_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const GameLobby_signin_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class GameLobby_signin_pargs {
 public:


  virtual ~GameLobby_signin_pargs() throw();
  const std::string* username;
  const std::string* password;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _GameLobby_signin_result__isset {
  _GameLobby_signin_result__isset() : success(false), e(false) {}
  bool success :1;
  bool e :1;
} _GameLobby_signin_result__isset;

class GameLobby_signin_result {
 public:

  GameLobby_signin_result(const GameLobby_signin_result&);
  GameLobby_signin_result& operator=(const GameLobby_signin_result&);
  GameLobby_signin_result() : success(0) {
  }

  virtual ~GameLobby_signin_result() throw();
  bool success;
  InvalidOperation e;

  _GameLobby_signin_result__isset __isset;

  void __set_success(const bool val);

  void __set_e(const InvalidOperation& val);

  bool operator == (const GameLobby_signin_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(e == rhs.e))
      return false;
    return true;
  }
  bool operator != (const GameLobby_signin_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const GameLobby_signin_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _GameLobby_signin_presult__isset {
  _GameLobby_signin_presult__isset() : success(false), e(false) {}
  bool success :1;
  bool e :1;
} _GameLobby_signin_presult__isset;

class GameLobby_signin_presult {
 public:


  virtual ~GameLobby_signin_presult() throw();
  bool* success;
  InvalidOperation e;

  _GameLobby_signin_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _GameLobby_fetch_game_args__isset {
  _GameLobby_fetch_game_args__isset() : g(false) {}
  bool g :1;
} _GameLobby_fetch_game_args__isset;

class GameLobby_fetch_game_args {
 public:

  GameLobby_fetch_game_args(const GameLobby_fetch_game_args&);
  GameLobby_fetch_game_args& operator=(const GameLobby_fetch_game_args&);
  GameLobby_fetch_game_args() : g((Game::type)0) {
  }

  virtual ~GameLobby_fetch_game_args() throw();
  Game::type g;

  _GameLobby_fetch_game_args__isset __isset;

  void __set_g(const Game::type val);

  bool operator == (const GameLobby_fetch_game_args & rhs) const
  {
    if (!(g == rhs.g))
      return false;
    return true;
  }
  bool operator != (const GameLobby_fetch_game_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const GameLobby_fetch_game_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class GameLobby_fetch_game_pargs {
 public:


  virtual ~GameLobby_fetch_game_pargs() throw();
  const Game::type* g;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _GameLobby_fetch_game_result__isset {
  _GameLobby_fetch_game_result__isset() : success(false) {}
  bool success :1;
} _GameLobby_fetch_game_result__isset;

class GameLobby_fetch_game_result {
 public:

  GameLobby_fetch_game_result(const GameLobby_fetch_game_result&);
  GameLobby_fetch_game_result& operator=(const GameLobby_fetch_game_result&);
  GameLobby_fetch_game_result() : success(0) {
  }

  virtual ~GameLobby_fetch_game_result() throw();
  bool success;

  _GameLobby_fetch_game_result__isset __isset;

  void __set_success(const bool val);

  bool operator == (const GameLobby_fetch_game_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const GameLobby_fetch_game_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const GameLobby_fetch_game_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _GameLobby_fetch_game_presult__isset {
  _GameLobby_fetch_game_presult__isset() : success(false) {}
  bool success :1;
} _GameLobby_fetch_game_presult__isset;

class GameLobby_fetch_game_presult {
 public:


  virtual ~GameLobby_fetch_game_presult() throw();
  bool* success;

  _GameLobby_fetch_game_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class GameLobbyClient : virtual public GameLobbyIf {
 public:
  GameLobbyClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  GameLobbyClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  bool signup(const std::string& username, const std::string& password);
  void send_signup(const std::string& username, const std::string& password);
  bool recv_signup();
  bool signin(const std::string& username, const std::string& password);
  void send_signin(const std::string& username, const std::string& password);
  bool recv_signin();
  bool fetch_game(const Game::type g);
  void send_fetch_game(const Game::type g);
  bool recv_fetch_game();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class GameLobbyProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<GameLobbyIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (GameLobbyProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_signup(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_signin(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_fetch_game(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  GameLobbyProcessor(boost::shared_ptr<GameLobbyIf> iface) :
    iface_(iface) {
    processMap_["signup"] = &GameLobbyProcessor::process_signup;
    processMap_["signin"] = &GameLobbyProcessor::process_signin;
    processMap_["fetch_game"] = &GameLobbyProcessor::process_fetch_game;
  }

  virtual ~GameLobbyProcessor() {}
};

class GameLobbyProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  GameLobbyProcessorFactory(const ::boost::shared_ptr< GameLobbyIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< GameLobbyIfFactory > handlerFactory_;
};

class GameLobbyMultiface : virtual public GameLobbyIf {
 public:
  GameLobbyMultiface(std::vector<boost::shared_ptr<GameLobbyIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~GameLobbyMultiface() {}
 protected:
  std::vector<boost::shared_ptr<GameLobbyIf> > ifaces_;
  GameLobbyMultiface() {}
  void add(boost::shared_ptr<GameLobbyIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  bool signup(const std::string& username, const std::string& password) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->signup(username, password);
    }
    return ifaces_[i]->signup(username, password);
  }

  bool signin(const std::string& username, const std::string& password) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->signin(username, password);
    }
    return ifaces_[i]->signin(username, password);
  }

  bool fetch_game(const Game::type g) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->fetch_game(g);
    }
    return ifaces_[i]->fetch_game(g);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class GameLobbyConcurrentClient : virtual public GameLobbyIf {
 public:
  GameLobbyConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  GameLobbyConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  bool signup(const std::string& username, const std::string& password);
  int32_t send_signup(const std::string& username, const std::string& password);
  bool recv_signup(const int32_t seqid);
  bool signin(const std::string& username, const std::string& password);
  int32_t send_signin(const std::string& username, const std::string& password);
  bool recv_signin(const int32_t seqid);
  bool fetch_game(const Game::type g);
  int32_t send_fetch_game(const Game::type g);
  bool recv_fetch_game(const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
