// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "GameLobby.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class GameLobbyHandler : virtual public GameLobbyIf {
 public:
  GameLobbyHandler() {
    // Your initialization goes here
  }

  bool sign_up(const std::string& username, const std::string& password) {
    // Your implementation goes here
    printf("sign_up\n");
  }

  bool sign_in(const std::string& username, const std::string& password) {
    // Your implementation goes here
    printf("sign_in\n");
  }

  void fetch_game(Path& _return, const Game::type g) {
    // Your implementation goes here
    printf("fetch_game\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<GameLobbyHandler> handler(new GameLobbyHandler());
  shared_ptr<TProcessor> processor(new GameLobbyProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

